debug

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -39,9 +39,10 @@ jobs:
           echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
           echo "DEBUG: Setting image output to $IMAGE"
 
-      - name: Debug Output Image
+      - name: Debug Step Output
         run: |
-          echo "DEBUG: Image Output = ${{ steps.get-image.outputs.image }}"
+          echo "DEBUG: Step Output Image -> ${{ steps.get-image.outputs.image }}"
+          cat "$GITHUB_OUTPUT" || echo "DEBUG: GITHUB_OUTPUT not found!"
 
   deploy_dev:
     runs-on: ubuntu-20.04
@@ -58,16 +59,9 @@ jobs:
           echo "DEBUG: GITHUB_REF: ${{ github.ref }}"
           echo "DEBUG: GITHUB_REF_NAME: ${{ github.ref_name }}"
 
-      - name: Check Passed Image
-        run: |
-          echo "DEBUG: Needs.build.outputs.image = ${{ needs.build.outputs.image }}"
-
       - name: Print Image Name
         run: |
           echo "Image from build: ${{ needs.build.outputs.image }}"
-
-      - name: Print Output Environments
-        run: echo "This is Development Environment"
 
   deploy__prod:
     runs-on: ubuntu-20.04
